##
## Makefile for  in /home/charvo_a/rush/visualizer/game
## 
## Made by Nicolas Charvoz
## Login   <charvo_a@epitech.net>
## 
## Started on  Mon May 12 14:17:17 2014 Nicolas Charvoz
## Last update Mon May 12 14:18:22 2014 Nicolas Charvoz
##

all:
	gcc -o game *.c -lSDL -lSDL_image -lSDL_ttf


clean:
	rm game

re:	clean all
