##
## Makefile for  in /home/charvo_a/visualizer
## 
## Made by Nicolas Charvoz
## Login   <charvo_a@epitech.net>
## 
## Started on  Sun May 11 17:45:21 2014 Nicolas Charvoz
## Last update Sun May 11 18:01:46 2014 Nicolas Charvoz
##

all:
	gcc ./src/*.c -o visualiser -lSDL -lSDL_image -lSDL_ttf -g3 -W -Wextra -Wall
	cp -r ./res/* /tmp/

clean:
	rm /tmp/*.*
